1. terminate called after throwing an instance of 'std::invalid_argument' what(): stoi

stoi的参数是无效的，可能并不能完成转换任务

- `std::invalid_argument` **：没有可执行的转换**
- `std::out_of_range` ：转换后的值超出了结果类型的范围，或者如果底层函数（std::strtol或std::strtoll）将errno设置为ERANGE。

2. reference binding to null pointer of type 'const value_type'

数组访问越界，可能是没有初始化的原因

